#Titles only works for spigot/craftbukkit 1.8 or higher + protocol hack working
special:
   FancyBlockBreak: true
   UseBarApi: true
   UseTitle: true
info:
   list:
   - '&6&lThe TNTRun plugin by The_TadeSK'
   - '&6 '
   - '&6&lNow try and play'