name: TNTRun
main: tntrun.TNTRun
softdepend: [WorldEdit, Vault]
version: 4.0
author: _Shevchik_
commands:
  tntrunsetup:
    description: TNTRun arena setup commands
    aliases: trsetup
    usage: Command is invalid, use /tr cmds for view all commands
  tntrun:
    description: TNTRun game commands
    aliases: tr
    usage: Please use /tr help for more info
  tntrunconsole:
    description: TNTRun console commands
    aliases: trconsole
    usage: Command is invalid, please use /tr cmds